### PR TITLE
made enhancements for  issue #158

### PR DESCRIPTION
**Pull request by Nimit1775**
made changes for issue #158 
adding google drive link for a short video

  https://drive.google.com/drive/folders/1tY3wjl0dWQrD_b25GXu9KPSTFipxybEu?usp=drive_link
( in the screen recording , as my system is set on dark mode it shows dark when clicked on system and the dark and light modes work perfectly individually too ) 

// summary of the changes  
made the system auto detect the mode  of the device and change it to that mode automatically and also added a dropdown with "dark" , "light" , "system" choices  

@iamparas0

### CODE REVIEW

**Comment by Nimit1775** [comment]
@iamparas0  if  you are merging kindly add the required labels too , this was a level 2 issue by the way

**Comment by iamparas0** [comment]
> @iamparas0 if you are merging this kindly add the required labels too , this was a level 2 issue by the way

WhatsApp Image 2024-10-09 at 9 14 28 PM


i know , can you replace the mode shifting button with toggle like above , by default system and user can choose thier mode

**Comment by Nimit1775** [comment]
@iamparas0  basically instead of a dropdown which i have made you want this right  ?

**Comment by Nimit1775** [comment]
@iamparas0  so should i make new PR  , with this toggle option ?

**Comment by iamparas0** [comment]
> @iamparas0 so should i make new PR , with this toggle option ?

you can continue with this

**Comment by Nimit1775** [comment]
okay @iamparas0

**Comment by Nimit1775** [comment]
hey @iamparas0  made the changes as you requested , i have  made it as close as i could 
heres the video link = https://drive.google.com/drive/folders/1tY3wjl0dWQrD_b25GXu9KPSTFipxybEu?usp=drive_link

**Comment by iamparas0** [comment]
gre

> hey @iamparas0 made the changes as you requested , i have made it as close as i could heres the video link = https://drive.google.com/drive/folders/1tY3wjl0dWQrD_b25GXu9KPSTFipxybEu?usp=drive_link



> hey @iamparas0 made the changes as you requested , i have made it as close as i could heres the video link = https://drive.google.com/drive/folders/1tY3wjl0dWQrD_b25GXu9KPSTFipxybEu?usp=drive_link

did you commited also cause i have deployed so theres no change , please check and let me know so i can merge it

**Comment by Nimit1775** [comment]
> gre
> 
> > hey @iamparas0 made the changes as you requested , i have made it as close as i could heres the video link = https://drive.google.com/drive/folders/1tY3wjl0dWQrD_b25GXu9KPSTFipxybEu?usp=drive_link
> 
> > hey @iamparas0 made the changes as you requested , i have made it as close as i could heres the video link = https://drive.google.com/drive/folders/1tY3wjl0dWQrD_b25GXu9KPSTFipxybEu?usp=drive_link
> 
> did you commited also cause i have deployed so theres no change , please check and let me know so i can merge it

Yes I did commit the changes , it was showing you had to Authorize the vercel deployment too .

**Comment by Nimit1775** [comment]
> > gre
> > > hey @iamparas0 made the changes as you requested , i have made it as close as i could heres the video link = https://drive.google.com/drive/folders/1tY3wjl0dWQrD_b25GXu9KPSTFipxybEu?usp=drive_link
> > 
> > 
> > > hey @iamparas0 made the changes as you requested , i have made it as close as i could heres the video link = https://drive.google.com/drive/folders/1tY3wjl0dWQrD_b25GXu9KPSTFipxybEu?usp=drive_link
> > 
> > 
> > did you commited also cause i have deployed so theres no change , please check and let me know so i can merge it
> 
> Yes I did commit the changes , it was showing you had to Authorize the vercel deployment too .

Are the changes not showing in the deployment?

**Pull request merged**
