### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by kartikey369-ind**
added CODE_OF_CONDUCT.md 
resolves issue number  https://github.com/iamparas0/TIC-TAC-TOE/issues/18

### CODE REVIEW

**Comment by iamparas0** [comment]
> added CODE_OF_CONDUCT.md resolves issue number #18

please put a ss so i can review and merge

**Comment by kartikey369-ind** [comment]
Screenshot (14)

Screenshot (11)
Screenshot (12)
Screenshot (13)
Screenshot (9)
Screenshot (10)

**Comment by iamparas0** [comment]
did you used chatgpt or something else , please trim the matter and use points with minimal sentences cause no one has span to read whole right

**Comment by kartikey369-ind** [comment]
Closed

**Pull request closed without merging**
