### PR TITLE
Resolved Tie Indication Issue in Tic-Tac-Toe Game

### PR DESCRIPTION
**Pull request by shrutisk0405**
I've added the logic for displaying the draw message in Game.js and updated the CSS to ensure it appears consistently with other messages. 
Additionally, I would like to implement a feature that shows whose turn it is on the game board. Could you please assign this task to me?" 
Please assign it under gssoc-ext and hacktoberfest2024 along with the level labels.

Screenshot 2024-10-20 160053

### CODE REVIEW

**Comment by Ritikabiswas** [comment]
hey do you need help with this vercel check error .I also faced the same problem so I thought to help 

{
    "rewrites":[
        {"source" : "./(.*)", "destination" : "/"}
    ],
        "git": {
          "deploymentEnabled": {
            "main": false
          }
        }
      } write or paste this code in the vercel.json file it will not show error then

**Comment by shrutisk0405** [comment]
@Ritikabiswas  Thank You!!

**Comment by iamparas0** [comment]
> @Ritikabiswas Thank You!!

Please write your issue no. With #

**Comment by Ritikabiswas** [comment]
> > @Ritikabiswas Thank You!!
> 
> Please write your issue no. With #

#333

**Comment by shrutisk0405** [comment]
This is issue no. #348

**Pull request merged**
