### PR TITLE
Home page navigation

### PR DESCRIPTION
**Pull request by mraghavi**
Hey @iamparas0  , I made the changes , **made the default page as home page**, so when you click on home page it doesn't navigate to another "home" route , instead the default home page is in itself the home page , here I'm attaching two videos before and after how it works , have a look and let me know
Thank you!!
here's the **before video** , it shows how the website takes us to another page when we click on home!
https://github.com/user-attachments/assets/7a895585-1866-400d-a01a-6313b01b5f12

here's the **after video** , I showed how the website's default page is the home page and it doesn't go to another page when clicked on home page , for comparision , I also clicked on another pages like "about, rules" they all go to another pages but home page stays default page of website , please have a look

https://github.com/user-attachments/assets/bdbfe591-5640-479f-a350-3227298c975c

### CODE REVIEW

**Comment by mraghavi** [comment]
Hey @iamparas0 , can you merge it under Home Page Navigation #322 which is under gssoc-ext level-2

**Comment by Ritikabiswas** [comment]
hey do you need help with this vercel check error .I also faced the same problem so I thought to help

{
"rewrites":[
{"source" : "./(.*)", "destination" : "/"}
],
"git": {
"deploymentEnabled": {
"main": false
}
}
} write or paste this code in the vercel.json file it will not show error then

**Comment by mraghavi** [comment]
> Screenshot_2024-10-21-12-42-18-16

hey, it didnt work though for me!

**Comment by Ritikabiswas** [comment]
Did you created any branch of the fork repository or you directly changed in the vs code main branch .I changed in the main branch and it worked for me

**Comment by mraghavi** [comment]
> Did you created any branch of the fork repository or you directly changed in the vs code main branch .I changed in the main branch and it worked for me

ohh, may be any team member need to authorize it, cos as per the instructions we were supposed to create another branch right, so created another branch for it

**Comment by mraghavi** [comment]
@iamparas0 hey can you merge it, or let me know if I need to work from main branch?

**Pull request merged**
