### PR TITLE
Follow us section added 

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
Added follow us section  
image

### CODE REVIEW

**Review by KapuluruBhuvaneswariVspdbct — COMMENTED** [review]
changes to follow us

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
please go through this

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Made changes to the follow us section according to the theme of website
tictactoefoot

**Comment by iamparas0** [comment]
> Made changes to the follow us section according to the theme of website tictactoefoot

Screenshot_2024-10-09-15-50-24-641_com android chrome


Please decrease  the size of Icon and remove follow us text, and make it responsive so it can not look odd in phone

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
ok i will do it

**Pull request merged**
