### PR TITLE
Fix Toggle Positioning and Add Win Popup in Tic Tac Toe

### PR DESCRIPTION
**Pull request by TornovDutta**
# Description
This PR addresses two issues in the Tic Tac Toe application: the positioning of the toggle switch and the implementation of a popup message that appears when a player wins. The CSS for the .toggle class has been updated to position it on the right side of the screen, enhancing accessibility. Additionally, a popup has been added to display the winner's name upon winning, improving user interaction. The toggle switch's position has been verified across different screen sizes, and the functionality of both the toggle and popup have been confirmed to work seamlessly.

### CODE REVIEW

**Comment by TornovDutta** [comment]
@sanjay-kv @iamparas0 @BaraniVA @Damini2004 .
please label it.

**Comment by TornovDutta** [comment]
This is PR of #79

**Comment by TornovDutta** [comment]
@sanjay-kv @iamparas0 @BaraniVA @Damini2004 
please Label the PR

**Comment by TornovDutta** [comment]
@iamparas0 , is this PR okay?

**Comment by TornovDutta** [comment]
@iamparas0 please label it , and the pr

**Comment by TornovDutta** [comment]
@iamparas0 please check the PR

**Comment by iamparas0** [comment]
> @iamparas0 please check the PR

There's a conflicting with existing code so wait I am resolving it and will merge it

**Comment by TornovDutta** [comment]
@iamparas0 please marge the PR

**Comment by TornovDutta** [comment]
@iamparas0 please check the Pull Requested

**Pull request merged**
