### PR TITLE
Update App.js to add a Result Board

### PR DESCRIPTION
**Pull request by bm9240**
Pull Request for issue #69 
So I have added a Basic score board that gets updated when one of the players win and maintains the record until the game is restarted.

firstly, I have accepted the names of the players which is not compulsory as they could play as Player X and Player O.
For the score board 2 buttons were required which were continue and restart to make sure that the results are updated properly.
After the player clicks restart the final winner name gets displayed for 2s. 
Here's a video of the game after these changes:

https://github.com/user-attachments/assets/24f31410-4bf0-45f1-a4d4-81f86fd5399d

It was great to contribute to this Project !!
Thank You !!

### CODE REVIEW

**Comment by bm9240** [comment]
Please let me know if some changes are required.

**Comment by bm9240** [comment]
Hey @iamparas0,
Is there any issue with my PR.
I would really like to know if any changes are required 
Thank You!!

**Comment by iamparas0** [comment]
> Pull Request for issue #69 So I have added a Basic score board that gets updated when one of the players win and maintains the record until the game is restarted.
> 
> firstly, I have accepted the names of the players which is not compulsory as they could play as Player X and Player O. For the score board 2 buttons were required which were continue and restart to make sure that the results are updated properly. After the player clicks restart the final winner name gets displayed for 2s. Here's a video of the game after these changes:
> 
>  TIC_TAC_TOE.1.mp4 
> It was great to contribute to this Project !! Thank You !!

you did really a great job please fix the scoreboard for night mode then i will merge it

**Comment by bm9240** [comment]
Hello @iamparas0 ,
I have  fixed the scoreboard as per feedback.

**Comment by bm9240** [comment]
Screenshot (193)
Here is the demo of the changes made

**Comment by bm9240** [comment]
Hi @iamparas0,
Is this ok now ?

**Comment by iamparas0** [comment]
> Hi @iamparas0, Is this ok now ?

Please give me some time I am reviewing it cause it conflict with existing code

**Comment by bm9240** [comment]
Okay !!

**Pull request merged**
