### PR TITLE
Adding Restart Button 

### PR DESCRIPTION
**Pull request by aditiverma-21**
Issue no #289

image
Added the button to RESTART BUTTON

### CODE REVIEW

**Comment by aditiverma-21** [comment]
@iamparas0 can you please check this?

**Comment by aditiverma-21** [comment]
@iamparas0 Please check this??!!

**Comment by aditiverma-21** [comment]
@sanjay-kv @iamparas0  WILL THIS PR BE APPROVED? LABELED?

**Comment by sanjay-kv** [comment]
@aditiverma-21 you have to tag the project admin, I wont be able to comment on others repo. if any label issue after merging I can help

**Comment by aditiverma-21** [comment]
@sanjay-kv Thank you for the help but the admin is not responding

**Comment by aditiverma-21** [comment]
Thank you @iamparas0

**Pull request merged**
