### PR TITLE
DONE ...

### PR DESCRIPTION
**Pull request by SaanyaGarg5**

### CODE REVIEW

**Comment by SaanyaGarg5** [comment]
pls. .check now

**Comment by SaanyaGarg5** [comment]
@iamparas0 
in this too it is showing the same error ... 
so ,what to do now?

**Comment by iamparas0** [comment]
> pls. .check now


Screenshot (52)

unable deploy and merge due to this error

**Comment by SaanyaGarg5** [comment]
> > pls. .check now
> 
> Screenshot (52)
> 
> unable deploy and merge due to this error

okay ..are you resolving this issue?

**Comment by iamparas0** [comment]
> > > pls. .check now
> > 
> > 
> > Screenshot (52)
> > unable deploy and merge due to this error
> 
> okay ..are you resolving this issue?

no i cannot , because its yours i have no access , you have to resolve .due to this i am unable to deploy and merge

**Comment by SaanyaGarg5** [comment]
> > > > pls. .check now
> > > 
> > > 
> > > Screenshot (52)
> > > unable deploy and merge due to this error
> > 
> > 
> > okay ..are you resolving this issue?
> 
> no i cannot , because its yours i have no access , you have to resolve .due to this i am unable to deploy and merge

but my work was to add the footer part which  i have done. .and  not to correct something else..

**Comment by iamparas0** [comment]
> > > > > pls. .check now
> > > > 
> > > > 
> > > > Screenshot (52)
> > > > unable deploy and merge due to this error
> > > 
> > > 
> > > okay ..are you resolving this issue?
> > 
> > 
> > no i cannot , because its yours i have no access , you have to resolve .due to this i am unable to deploy and merge
> 
> but my work was to add the footer part which i have done. .and not to correct something else..

i know but when i'm trying to deploy and merge this error throws due to this it failed to merge and deploy

**Comment by SaanyaGarg5** [comment]
I can't change it further..
pls resolve the issue and give me the points for my contribution...

**Pull request merged**
